apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: heb-inventory
  namespace: heb-inventory
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: heb-inventory
