apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heb-inventory.fullname" . }}-secrets
  labels:
    {{- include "heb-inventory.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
  {{- if .Values.postgres.enabled }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  {{- end }}
